### ISSUE TITLE
Besides this patch and page_balancing.c, what other changes have been made in kernel?

### ISSUE THREAD

**Issue by skpupil** [csl-ajou/AutoTiering#1]
Besides this patch and page_balancing.c, what other changes have been made in kernel?

**Comment by jhk16** [comment]
@skpupil 
I mostly modified [mm/page_alloc.c](https://github.com/csl-ajou/AutoTiering/blob/d125a12c0cde2ce411b5a4a5cd17e5a723ac38c5/linux-5.3.0-autotiering/mm/page_alloc.c#L9149) for initializing kernel threads demoting pages on the background with reserved pages.

In [mm/migrate.c](https://github.com/csl-ajou/AutoTiering/blob/d125a12c0cde2ce411b5a4a5cd17e5a723ac38c5/linux-5.3.0-autotiering/mm/migrate.c#L2378), there are real page migration(including promotion and demotion) processes.

In [mm/mprotect.c](https://github.com/csl-ajou/AutoTiering/blob/d125a12c0cde2ce411b5a4a5cd17e5a723ac38c5/linux-5.3.0-autotiering/mm/mprotect.c#L109), there is a page scanning process for access tracking by unmapping pages, which caused minor faults.

I think these things are the primary change points in our kernel.
